Erp\Bundle\SystemBundle\Entity\SystemClient:
  type: entity
  #repositoryClass: Erp\Bundle\SystemBundle\Infrastructure\ORM\Repository\SystemClientRepository
  table: system_client
  inheritanceType: JOINED
  fields:
    secret:
      type: string
      length: 128
      nullable: false
    redirectUris:
      type: simple_array
      nullable: true
    allowedGrantTypes:
      type: simple_array
      nullable: true
