Erp\Bundle\SystemBundle\Entity\SystemUser:
  type: entity
  repositoryClass: Erp\Bundle\SystemBundle\Infrastructure\ORM\Repository\SystemUserRepository
  table: system_user
  inheritanceType: JOINED
  fields:
    password:
      type: string
      length: 128
      nullable: false
