parameters:
  container.autowiring.strict_mode: true

services:

  _defaults:
    # automatically injects dependencies in your services
    autowire: true
    # automatically registers your services as commands, event subscribers, etc.
    autoconfigure: true
    # this means you cannot fetch services directly from the container via $container->get()
    # if you need to do this, you can override this setting on individual services
    public: false

  Erp\Bundle\SystemBundle\:
    resource: '../../*'
    # you can exclude directories or files
    # but if a service is unused, it's removed anyway
    exclude: '../../{Collection,Entity,Infrastructure/ORM/Repository}'

  Erp\Bundle\SystemBundle\Controller\:
    resource: '../../Controller'
    tags: ['controller.service_arguments']

  #--------- global --------------
  # erp_system.service.user_provider:
  #   class: Erp\Bundle\SystemBundle\Service\UserProvider
  #   arguments:
  #     - "@erp_system.service.query.system_user"

  # CQRS
  #Erp\Bundle\SystemBundle\Infrastructure\ORM\Service\SystemCommandHandlerService:
  #  arguments:
  #    - "@doctrine.orm.default_entity_manager"

  #Erp\Bundle\SystemBundle\Domain\CQRS\SystemCommandHandler: '@Erp\Bundle\SystemBundle\Infrastructure\ORM\Service\SystemCommandHandlerService'

  Erp\Bundle\SystemBundle\Domain\CQRS\SystemAccountQuery: '@Erp\Bundle\SystemBundle\Infrastructure\ORM\Service\SystemAccountQueryService'
  Erp\Bundle\SystemBundle\Domain\CQRS\SystemUserQuery: '@Erp\Bundle\SystemBundle\Infrastructure\ORM\Service\SystemUserQueryService'
  Erp\Bundle\SystemBundle\Domain\CQRS\SystemGroupQuery: '@Erp\Bundle\SystemBundle\Infrastructure\ORM\Service\SystemGroupQueryService'

  #Entity Listerner
  Erp\Bundle\SystemBundle\Infrastructure\ORM\Listener\SystemUserListener:
    class: Erp\Bundle\SystemBundle\Infrastructure\ORM\Listener\SystemUserListener
    tags:
      - { name: doctrine.orm.entity_listener, entity: Erp\Bundle\SystemBundle\Entity\SystemUser, event: preFlush }

  Erp\Bundle\SystemBundle\Infrastructure\ORM\Listener\SystemGroupListener:
    class: Erp\Bundle\SystemBundle\Infrastructure\ORM\Listener\SystemGroupListener
    tags:
      - { name: doctrine.orm.entity_listener, entity: Erp\Bundle\SystemBundle\Entity\SystemGroup, event: preFlush }
