Erp\Bundle\SystemBundle\Entity\SystemAccount:
  access_type: property
  properties:
    individualRoles:
      type: array<string>
    systemGroups:
      type: Erp\Bundle\CoreBundle\Collection\ArrayCollection<Erp\Bundle\SystemBundle\Entity\SystemGroup>
      max_depth: 1
  virtual_properties:
    getRealRoles:
      serialized_name: roles
      type: array<string>
      max_depth: 1
